version: '3.1'

services:

  dbMongo:
    image: mongo
    restart: always
    volumes:
      - /ssd/dblib/mongodb:/data/db
#    ports:
#      - 27017:27017
#    deploy:
#      placement:
#        constraints: [node.role == manager]

# Use root/example as user/password credentials
  dbMysql:
    image: mysql
    restart: always
    volumes:
      - /ssd/anders/work/RGD/RGDdev/sqlinit:/docker-entrypoint-initdb.d
      - /ssd/dblib/mysql:/var/lib/mysql
#    ports:
#      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rgd
#    deploy:
#      placement:
#        constraints: [node.role == manager]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rgd:
    image: rgddev
    ports:
      - 8084:8085
    volumes:
      - /ssd/anders/work/RGD/RGDdev:/gedMerge
    links:
      - dbMongo
      - dbMysql
    depends_on:
      - dbMongo
      - dbMysql
